name: 'test'

on:
  push:
    branches:
    - 'main'
    tags:
    - '*'
  pull_request:
    branches:
    - 'main'
  workflow_dispatch:

jobs:
  test:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: 'actions/checkout@v3'

    - uses: 'actions/setup-go@v3'
      with:
        go-version: '1.17'

    - run: 'make test-acc'
